### ISSUE TITLE
Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/nodejs-skynet#150]
Hello m-cat

I have just cleded "SkynetLabs/nodejs-skynet".
Next I changed the version to "4.1.0" in "package.json", and "yarn test".
All tests run clean. Great.

After that, in "package.json" I changed the version to "4.2.0-beta" because I have the "client.getFileContentBinary" and "client.getFileContentBinaryHns" still wanted to integrate in "SkynetLabs/nodejs-skynet".

I tested "scripts/skydb.js" and "scripts/skydb_v2.js", and everything ok.
Then I executed "Yarn Test".
And there are many errors.

Everywhere the same error from version "4.2.0-beta" upwards:
`Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'`

What's going on there?
I haven't changed anything on the code, just the "package.json"!

Hopefully you can help me find out the problem.

Here are the complete errors:
```
  ● SkyDB V1 › db.setDataLink › should be a dataLink set

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      29 |   describe("db.setDataLink", () => {
      30 |     it("should be a dataLink set", async () => {
    > 31 |       await client.db.setDataLink(privateKey, dataKey, dataLink);
         |       ^
      32 |     });
      33 |   });
      34 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.setDataLink (node_modules/skynet-js/dist/cjs/skydb.js:140:5)
      at Object.<anonymous> (src/skydb.test.js:31:7)

  ● SkyDB V1 › db.setEntryData › should set entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      35 |   describe("db.setEntryData", () => {
      36 |     it("should set entryData", async () => {
    > 37 |       const receivedData = await client.db.setEntryData(privateKey, dataKey, rawEntryData);
         |                            ^
      38 |
      39 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      40 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at Object.<anonymous> (src/skydb.test.js:37:28)

  ● SkyDB V1 › db.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      43 |   describe("db.getEntryData", () => {
      44 |     it("should get entryData", async () => {
    > 45 |       const receivedData = await client.db.getEntryData(publicKey, dataKey);
         |                            ^
      46 |
      47 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      48 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getEntryData (node_modules/skynet-js/dist/cjs/skydb.js:162:19)
      at Object.<anonymous> (src/skydb.test.js:45:28)

  ● SkyDB V1 › db.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      51 |   describe("db.getRawBytes", () => {
      52 |     it("should get rawBytes", async () => {
    > 53 |       const receivedData = await client.db.getRawBytes(publicKey, dataKey);
         |                            ^
      54 |
      55 |       await expect(formatSkylink(receivedData["dataLink"])).toEqual(dataLink);
      56 |       await expect("[" + receivedData["data"] + "]").toEqual(rawBytesData);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getRawBytes (node_modules/skynet-js/dist/cjs/skydb.js:246:19)
      at Object.<anonymous> (src/skydb.test.js:53:28)

  ● SkyDB V1 › db.setJSON › should set jsonData to skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      59 |
      60 |   // Fetch the current value to find out the revision.
    > 61 |   const signedEntry = await client.registry.getEntry(publicKey, dataKey, DEFAULT_GET_ENTRY_OPTIONS);
         |                       ^
      62 |
      63 |   const revision = getNextRevisionFromEntry(signedEntry.entry);
      64 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getOrCreateRegistryEntry (src/skydb.js:61:23)
      at SkynetClient.setJSONdbV1 (src/skydb.js:31:31)
      at Object.<anonymous> (src/skydb.test.js:62:28)

  ● SkyDB V1 › db.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      68 |   describe("db.getJSON", () => {
      69 |     it("should get jsonData from skydb", async () => {
    > 70 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
         |                            ^
      71 |
      72 |       await expect(receivedData.data).toEqual(data);
      73 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getJSON (node_modules/skynet-js/dist/cjs/skydb.js:44:19)
      at Object.<anonymous> (src/skydb.test.js:70:28)

  ● SkyDB V1 › db.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      76 |   describe("db.deleteJSON", () => {
      77 |     it("should delete jsonData on skydb", async () => {
    > 78 |       await client.db.deleteJSON(privateKey, dataKey);
         |       ^
      79 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
      80 |
      81 |       await expect(receivedData.data).toEqual(null);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.deleteJSON (node_modules/skynet-js/dist/cjs/skydb.js:119:5)
      at Object.<anonymous> (src/skydb.test.js:78:7)

 FAIL  src/skydb_v2.test.js
  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:229:23

  ● SkyDB V2 › dbV2.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:329:23

  ● SkyDB V2 › dbV2.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23
```

**Comment by parajbs** [comment]
Hello **m-cat**,

i reopened the message here because the problem is still there.

i've been looking for a needle in a haystack for a long time.
then I went back to the beginning and took a close look at the problem.

**since I said that all manual tests of "scripts/skydb.js" and "scripts/skydb_v2.js" are OK. which is the case.
this means that it cannot be due to the default portal "https://siasky.net".**

Then I searched the files "skydb.test.js" and "skydb_v2.test.js" for a solution and tested everything I could.

Then later I worked out a solution.

**here the solution:**
I only had to comment out two lines in the files "skydb.test.js" and "skydb_v2.test.js":

`// jest.mock("axios");`

and

`// axios.mockResolvedValue({ data: { skylink } });`

After that everything went OK.
I think I didn't understand what "axios" meant, so I commented it out.

I was all the more surprised that everything went smoothly after that.
I'm not sure if it was correct, but it works.

**Maybe you have another second better solution?**

maybe "axios" is also important?
Then you have to help me, otherwise I have no idea how to get rid of the bugs.
